/*
 Navicat Premium Data Transfer

 Source Server         : oracle
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Host           : localhost:1521
 Source Schema         : ZOTION

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 01/08/2023 09:29:30
*/


-- ----------------------------
-- Table structure for DAILY_REPORT
-- ----------------------------
DROP TABLE "ZOTION"."DAILY_REPORT";
CREATE TABLE "ZOTION"."DAILY_REPORT" (
  "WAREHOUSE_CODE" VARCHAR2(100 BYTE),
  "MATERIAL_CODE" VARCHAR2(100 BYTE),
  "REPORT_DATE" DATE,
  "START_QUANTITY" NUMBER,
  "INBOUND_QUANTITY" NUMBER,
  "OUTBOUND_QUANTITY" NUMBER,
  "ENDBOUND_QUANTITY" NUMBER
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Records of DAILY_REPORT
-- ----------------------------
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231003', TO_DATE('2023-08-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '41', NULL, NULL, '41');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231005', TO_DATE('2023-07-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '5', NULL, NULL, '5');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '25', NULL, '1', '24');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231006', TO_DATE('2023-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '6', NULL, NULL, '6');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023002', 'M20231002', TO_DATE('2023-07-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '7', NULL, NULL, '7');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231002', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '22', NULL, NULL, '22');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231001', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '8', NULL, '3', '5');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023002', 'M20231001', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '11', NULL, '3', '8');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023002', 'M20231005', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '2', NULL, '2', '0');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023002', 'M20231001', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '10', '3', '7');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231002', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '22', NULL, '22');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023002', 'M20231005', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '2', '2', '0');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231003', TO_DATE('2023-08-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '41', NULL, '41');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231005', TO_DATE('2023-07-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '5', NULL, '5');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231006', TO_DATE('2023-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '6', NULL, '6');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023002', 'M20231001', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '1', '3', '-2');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '19', '1', '18');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023002', 'M20231002', TO_DATE('2023-07-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '7', NULL, '7');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231001', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '8', '3', '5');
INSERT INTO "ZOTION"."DAILY_REPORT" VALUES ('W2023003', 'M20231003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '6', '1', '5');

-- ----------------------------
-- Table structure for INBOUND_DETAIL
-- ----------------------------
DROP TABLE "ZOTION"."INBOUND_DETAIL";
CREATE TABLE "ZOTION"."INBOUND_DETAIL" (
  "ID" NUMBER NOT NULL,
  "INBOUND_ORDER_CODE" VARCHAR2(255 BYTE) NOT NULL,
  "MATERIAL_CODE" VARCHAR2(255 BYTE) NOT NULL,
  "QUANTITY" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZOTION"."INBOUND_DETAIL"."ID" IS 'id';
COMMENT ON COLUMN "ZOTION"."INBOUND_DETAIL"."INBOUND_ORDER_CODE" IS '入库单号';
COMMENT ON COLUMN "ZOTION"."INBOUND_DETAIL"."MATERIAL_CODE" IS '物料编码';
COMMENT ON COLUMN "ZOTION"."INBOUND_DETAIL"."QUANTITY" IS '入库数量';

-- ----------------------------
-- Records of INBOUND_DETAIL
-- ----------------------------
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('3', 'I2023-1-002', 'M20231001', '10');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('4', 'I2023-1-003', 'M20231002', '22');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('6', 'I2023-1-005', 'M20231005', '2');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('7', 'I2023-1-006', 'M20231003', '41');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('9', 'I2023-1-008', 'M20231005', '5');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('11', 'I2023-1-010', 'M20231006', '6');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('1', 'I2023-1-001', 'M20231001', '1');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('5', 'I2023-1-004', 'M20231003', '19');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('8', 'I2023-1-007', 'M20231002', '7');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('10', 'I2023-1-009', 'M20231001', '8');
INSERT INTO "ZOTION"."INBOUND_DETAIL" VALUES ('12', 'I2023-1-011', 'M20231003', '6');

-- ----------------------------
-- Table structure for INBOUND_ORDER
-- ----------------------------
DROP TABLE "ZOTION"."INBOUND_ORDER";
CREATE TABLE "ZOTION"."INBOUND_ORDER" (
  "ID" NUMBER NOT NULL,
  "INBOUND_ORDER_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "WAREHOUSE_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "INBOUND_TIME" DATE NOT NULL,
  "OPERATOR" VARCHAR2(20 BYTE) NOT NULL,
  "CREATE_TIME" DATE NOT NULL,
  "REMARK" VARCHAR2(30 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZOTION"."INBOUND_ORDER"."INBOUND_ORDER_CODE" IS '入库单号';
COMMENT ON COLUMN "ZOTION"."INBOUND_ORDER"."WAREHOUSE_CODE" IS '仓库编码';
COMMENT ON COLUMN "ZOTION"."INBOUND_ORDER"."INBOUND_TIME" IS '入库时间';
COMMENT ON COLUMN "ZOTION"."INBOUND_ORDER"."OPERATOR" IS '入库人';
COMMENT ON COLUMN "ZOTION"."INBOUND_ORDER"."CREATE_TIME" IS '录入时间';
COMMENT ON COLUMN "ZOTION"."INBOUND_ORDER"."REMARK" IS '备注';
COMMENT ON TABLE "ZOTION"."INBOUND_ORDER" IS '入库单表';

-- ----------------------------
-- Records of INBOUND_ORDER
-- ----------------------------
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('3', 'I2023-1-002', 'W2023002', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '李某某', TO_DATE('2023-07-31 23:52:11', 'SYYYY-MM-DD HH24:MI:SS'), '新增入库单');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('4', 'I2023-1-003', 'W2023003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', TO_DATE('2023-07-31 23:52:19', 'SYYYY-MM-DD HH24:MI:SS'), '新增入库单');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('6', 'I2023-1-005', 'W2023002', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', TO_DATE('2023-07-31 23:52:36', 'SYYYY-MM-DD HH24:MI:SS'), '哈哈哈');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('7', 'I2023-1-006', 'W2023003', TO_DATE('2023-08-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '赵某某', TO_DATE('2023-08-01 09:24:27', 'SYYYY-MM-DD HH24:MI:SS'), '嘎嘎嘎');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('9', 'I2023-1-008', 'W2023003', TO_DATE('2023-07-20 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', TO_DATE('2023-07-31 23:35:18', 'SYYYY-MM-DD HH24:MI:SS'), '哈哈哈哈');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('11', 'I2023-1-010', 'W2023003', TO_DATE('2023-07-29 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '李某某', TO_DATE('2023-07-31 23:36:28', 'SYYYY-MM-DD HH24:MI:SS'), 'vvvvv');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('1', 'I2023-1-001', 'W2023002', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '李某人', TO_DATE('2023-07-31 23:52:00', 'SYYYY-MM-DD HH24:MI:SS'), '新增入库单');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('5', 'I2023-1-004', 'W2023003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', TO_DATE('2023-07-31 23:52:27', 'SYYYY-MM-DD HH24:MI:SS'), '谢谢谢谢');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('8', 'I2023-1-007', 'W2023002', TO_DATE('2023-07-11 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '李某某', TO_DATE('2023-07-31 23:34:38', 'SYYYY-MM-DD HH24:MI:SS'), '顶顶顶顶');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('10', 'I2023-1-009', 'W2023003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', TO_DATE('2023-07-31 23:55:30', 'SYYYY-MM-DD HH24:MI:SS'), '啵啵啵');
INSERT INTO "ZOTION"."INBOUND_ORDER" VALUES ('12', 'I2023-1-011', 'W2023003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', TO_DATE('2023-07-31 23:55:22', 'SYYYY-MM-DD HH24:MI:SS'), '哈哈哈');

-- ----------------------------
-- Table structure for INVENTORY
-- ----------------------------
DROP TABLE "ZOTION"."INVENTORY";
CREATE TABLE "ZOTION"."INVENTORY" (
  "ID" NUMBER NOT NULL,
  "WAREHOUSE_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "MATERIAL_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "QUANTITY" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZOTION"."INVENTORY"."WAREHOUSE_CODE" IS '仓库编码';
COMMENT ON COLUMN "ZOTION"."INVENTORY"."MATERIAL_CODE" IS '物料编码';
COMMENT ON COLUMN "ZOTION"."INVENTORY"."QUANTITY" IS '库存数量';
COMMENT ON TABLE "ZOTION"."INVENTORY" IS '库存表';

-- ----------------------------
-- Records of INVENTORY
-- ----------------------------
INSERT INTO "ZOTION"."INVENTORY" VALUES ('2', 'W2023003', 'M20231002', '22');
INSERT INTO "ZOTION"."INVENTORY" VALUES ('4', 'W2023002', 'M20231005', '2');
INSERT INTO "ZOTION"."INVENTORY" VALUES ('6', 'W2023003', 'M20231005', '3');
INSERT INTO "ZOTION"."INVENTORY" VALUES ('8', 'W2023003', 'M20231006', '4');
INSERT INTO "ZOTION"."INVENTORY" VALUES ('1', 'W2023002', 'M20231001', '11');
INSERT INTO "ZOTION"."INVENTORY" VALUES ('3', 'W2023003', 'M20231003', '66');
INSERT INTO "ZOTION"."INVENTORY" VALUES ('5', 'W2023002', 'M20231002', '7');
INSERT INTO "ZOTION"."INVENTORY" VALUES ('7', 'W2023003', 'M20231001', '8');

-- ----------------------------
-- Table structure for MATERIAL
-- ----------------------------
DROP TABLE "ZOTION"."MATERIAL";
CREATE TABLE "ZOTION"."MATERIAL" (
  "ID" NUMBER NOT NULL,
  "MATERIAL_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "MATERIAL_NAME" VARCHAR2(20 BYTE) NOT NULL,
  "UNIT" VARCHAR2(30 BYTE) NOT NULL,
  "MODEL" VARCHAR2(20 BYTE) NOT NULL,
  "SPECIFICATION" VARCHAR2(20 BYTE) NOT NULL,
  "MAINTAINER" VARCHAR2(20 BYTE) NOT NULL,
  "MODIFY_TIME" DATE NOT NULL,
  "REMARK" VARCHAR2(30 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZOTION"."MATERIAL"."MATERIAL_CODE" IS '物料编码';
COMMENT ON COLUMN "ZOTION"."MATERIAL"."MATERIAL_NAME" IS '物料名称';
COMMENT ON COLUMN "ZOTION"."MATERIAL"."UNIT" IS '单位';
COMMENT ON COLUMN "ZOTION"."MATERIAL"."MODEL" IS '型号';
COMMENT ON COLUMN "ZOTION"."MATERIAL"."SPECIFICATION" IS '规格';
COMMENT ON COLUMN "ZOTION"."MATERIAL"."MAINTAINER" IS '维护人员';
COMMENT ON COLUMN "ZOTION"."MATERIAL"."MODIFY_TIME" IS '维护时间';
COMMENT ON COLUMN "ZOTION"."MATERIAL"."REMARK" IS '备注';
COMMENT ON TABLE "ZOTION"."MATERIAL" IS '物料信息表';

-- ----------------------------
-- Records of MATERIAL
-- ----------------------------
INSERT INTO "ZOTION"."MATERIAL" VALUES ('1', 'M20231001', 'CPU处理器', '个', '酷睿i9', '8+32G', '李某人', TO_DATE('2023-07-31 23:08:19', 'SYYYY-MM-DD HH24:MI:SS'), '新增CPU处理器');
INSERT INTO "ZOTION"."MATERIAL" VALUES ('2', 'M20231002', 'GPU显卡', '个', 'RTX 4090', '256核', '章某人', TO_DATE('2023-07-31 23:11:01', 'SYYYY-MM-DD HH24:MI:SS'), '新增GPU显卡');
INSERT INTO "ZOTION"."MATERIAL" VALUES ('3', 'M20231003', '机械键盘', '个', 'IKBC', 'C87', '杨某人', TO_DATE('2023-07-31 23:14:03', 'SYYYY-MM-DD HH24:MI:SS'), '新增键盘物料');
INSERT INTO "ZOTION"."MATERIAL" VALUES ('6', 'M20231006', '鼠标', '个', '罗技', 'MX Master 3', '李某人', TO_DATE('2023-07-31 23:25:12', 'SYYYY-MM-DD HH24:MI:SS'), '新增鼠标物料');
INSERT INTO "ZOTION"."MATERIAL" VALUES ('5', 'M20231005', '固态硬盘', '个', 'SSD', 'S430c', '章某人', TO_DATE('2023-07-31 23:22:50', 'SYYYY-MM-DD HH24:MI:SS'), '新增固态硬盘');

-- ----------------------------
-- Table structure for OUTBOUND_DETAIL
-- ----------------------------
DROP TABLE "ZOTION"."OUTBOUND_DETAIL";
CREATE TABLE "ZOTION"."OUTBOUND_DETAIL" (
  "ID" NUMBER NOT NULL,
  "OUTBOUND_ORDER_CODE" VARCHAR2(255 BYTE) NOT NULL,
  "MATERIAL_CODE" VARCHAR2(255 BYTE) NOT NULL,
  "QUANTITY" NUMBER NOT NULL
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZOTION"."OUTBOUND_DETAIL"."ID" IS 'ID';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_DETAIL"."OUTBOUND_ORDER_CODE" IS '出库单号';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_DETAIL"."MATERIAL_CODE" IS '物料编码';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_DETAIL"."QUANTITY" IS '出库数量';

-- ----------------------------
-- Records of OUTBOUND_DETAIL
-- ----------------------------
INSERT INTO "ZOTION"."OUTBOUND_DETAIL" VALUES ('1', 'O2023-1-001', 'M20231001', '3');
INSERT INTO "ZOTION"."OUTBOUND_DETAIL" VALUES ('2', 'O2023-1-002', 'M20231005', '2');
INSERT INTO "ZOTION"."OUTBOUND_DETAIL" VALUES ('3', 'O2023-1-003', 'M20231003', '1');
INSERT INTO "ZOTION"."OUTBOUND_DETAIL" VALUES ('4', 'O2023-1-004', 'M20231002', '10');
INSERT INTO "ZOTION"."OUTBOUND_DETAIL" VALUES ('5', 'O2023-1-005', 'M20231006', '2');

-- ----------------------------
-- Table structure for OUTBOUND_ORDER
-- ----------------------------
DROP TABLE "ZOTION"."OUTBOUND_ORDER";
CREATE TABLE "ZOTION"."OUTBOUND_ORDER" (
  "ID" NUMBER NOT NULL,
  "OUTBOUND_ORDER_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "WAREHOUSE_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "OUTBOUND_TIME" DATE NOT NULL,
  "OPERATOR" VARCHAR2(20 BYTE) NOT NULL,
  "CREATE_TIME" VARCHAR2(20 BYTE) NOT NULL,
  "REMARK" VARCHAR2(30 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZOTION"."OUTBOUND_ORDER"."OUTBOUND_ORDER_CODE" IS '出库单号';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_ORDER"."WAREHOUSE_CODE" IS '仓库编码';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_ORDER"."OUTBOUND_TIME" IS '出库时间';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_ORDER"."OPERATOR" IS '录入人';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_ORDER"."CREATE_TIME" IS '录入时间';
COMMENT ON COLUMN "ZOTION"."OUTBOUND_ORDER"."REMARK" IS '备注';
COMMENT ON TABLE "ZOTION"."OUTBOUND_ORDER" IS '出库单表';

-- ----------------------------
-- Records of OUTBOUND_ORDER
-- ----------------------------
INSERT INTO "ZOTION"."OUTBOUND_ORDER" VALUES ('1', 'O2023-1-001', 'W2023002', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', '31-7月 -23', 'vvv');
INSERT INTO "ZOTION"."OUTBOUND_ORDER" VALUES ('2', 'O2023-1-002', 'W2023003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', '31-7月 -23', '嘎嘎嘎');
INSERT INTO "ZOTION"."OUTBOUND_ORDER" VALUES ('3', 'O2023-1-003', 'W2023003', TO_DATE('2023-07-31 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '张三', '31-7月 -23', '哈哈哈哈');
INSERT INTO "ZOTION"."OUTBOUND_ORDER" VALUES ('4', 'O2023-1-004', 'W2023003', TO_DATE('2023-07-05 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '李某某', '31-7月 -23', '牛牛牛牛牛');
INSERT INTO "ZOTION"."OUTBOUND_ORDER" VALUES ('5', 'O2023-1-005', 'W2023003', TO_DATE('2023-07-14 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'), '赵某某', '31-7月 -23', '哈哈哈');

-- ----------------------------
-- Table structure for WAREHOUSE
-- ----------------------------
DROP TABLE "ZOTION"."WAREHOUSE";
CREATE TABLE "ZOTION"."WAREHOUSE" (
  "ID" NUMBER NOT NULL,
  "WAREHOUSE_CODE" VARCHAR2(20 BYTE) NOT NULL,
  "WAREHOUSE_NAME" VARCHAR2(20 BYTE) NOT NULL,
  "MAINTAINER" VARCHAR2(20 BYTE) NOT NULL,
  "MODIFY_TIME" DATE NOT NULL,
  "REMARK" VARCHAR2(30 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "ZOTION"."WAREHOUSE"."WAREHOUSE_CODE" IS '仓库编码';
COMMENT ON COLUMN "ZOTION"."WAREHOUSE"."WAREHOUSE_NAME" IS '仓库名称';
COMMENT ON COLUMN "ZOTION"."WAREHOUSE"."MAINTAINER" IS '维护人';
COMMENT ON COLUMN "ZOTION"."WAREHOUSE"."MODIFY_TIME" IS '维护时间';
COMMENT ON COLUMN "ZOTION"."WAREHOUSE"."REMARK" IS '备注';
COMMENT ON TABLE "ZOTION"."WAREHOUSE" IS '仓库表';

-- ----------------------------
-- Records of WAREHOUSE
-- ----------------------------
INSERT INTO "ZOTION"."WAREHOUSE" VALUES ('3', 'W2023003', 'B库', '张某人', TO_DATE('2023-07-31 23:27:19', 'SYYYY-MM-DD HH24:MI:SS'), '新增仓库B');
INSERT INTO "ZOTION"."WAREHOUSE" VALUES ('2', 'W2023002', 'A库', '李某人', TO_DATE('2023-07-31 23:26:54', 'SYYYY-MM-DD HH24:MI:SS'), '新增仓库A');

-- ----------------------------
-- Function structure for DROP_RECORD_TABLE
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "ZOTION"."DROP_RECORD_TABLE" AS
BEGIN
	--检查表是否存在
	select count(*) into table_exists from user_tables where table_name = 'DAILY_REPORT';
	--表存在，则删除
	if table_exists > 0 then
		EXECUTE IMMEDIATE 'DROP TABLE DAILY_REPORT';
	end if;
	
	--创建表
	EXECUTE IMMEDIATE 'CREATE TABLE DAILY_REPORT (
		warehouse_code VARCHAR2(100),
		material_code VARCHAR2(100),
		report_date DATE,
		start_quantity NUMBER,
		inbound_quantity NUMBER,
		outbound_quantity NUMBER,
		endbound_quantity NUMBER
	)';
	
	END;
/

-- ----------------------------
-- Function structure for GENERATE_DAILY_REPORT
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "ZOTION"."GENERATE_DAILY_REPORT" AS
BEGIN
		-- 插入数据到日报表中
	insert into daily_report(warehouse_code,material_code,report_date,start_quantity)
	select a.warehouse_code,b.material_code,a.inbound_time,sum(b.quantity)
	from inbound_order a
	join inbound_detail b
	on a.inbound_order_code = b.inbound_order_code
	group by a.warehouse_code,b.material_code,a.inbound_time;
	
	insert into daily_report(warehouse_code,material_code,report_date,inbound_quantity)
	select a.warehouse_code,b.material_code,a.inbound_time,b.quantity
	from inbound_order a
	join inbound_detail b on a.inbound_order_code = b.inbound_order_code;
	
	for rec in (
		select a.material_code,b.outbound_time as outbound_time,sum(a.quantity) as outbound_quantity 
		from outbound_detail a
		join outbound_order b on a.outbound_order_code = b.outbound_order_code
		group by a.material_code,b.outbound_time
	)
	LOOP
	update daily_report set outbound_quantity = rec.outbound_quantity where material_code = rec.material_code and report_date = rec.outbound_time;
    END LOOP;

	update daily_report set endbound_quantity = NVL(start_quantity,0) + NVL(inbound_quantity, 0) - NVL(outbound_quantity, 0);
	commit;
END;
/

-- ----------------------------
-- Function structure for GET_RANDOM_NUMBER
-- ----------------------------
CREATE OR REPLACE
FUNCTION "ZOTION"."GET_RANDOM_NUMBER" AS
BEGIN
	-- 生成1到1000之间的随机数
	select TRUNC(DBMS_RANDOM.VALUE(1,1001)) INTO random_number from dual;
	
	RETURN random_number;
END;
/

-- ----------------------------
-- Function structure for RECOVER_DATA
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "ZOTION"."RECOVER_DATA" AS
BEGIN
	FOR rec IN (
			select start_quantity,inbound_quantity,outbound_quantity from daily_report
	) LOOP
			update daily_report set start_quantity = rec.start_quantity,
			endbound_quantity = rec.start_quantity + rec.inbound_quantity - rec.outbound_quantity; 
		END LOOP;
		
		commit;

END;
/

-- ----------------------------
-- Sequence structure for SEQ_INBOUND_DETAIL_ID
-- ----------------------------
DROP SEQUENCE "ZOTION"."SEQ_INBOUND_DETAIL_ID";
CREATE SEQUENCE "ZOTION"."SEQ_INBOUND_DETAIL_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_INBOUND_ORDER_ID
-- ----------------------------
DROP SEQUENCE "ZOTION"."SEQ_INBOUND_ORDER_ID";
CREATE SEQUENCE "ZOTION"."SEQ_INBOUND_ORDER_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_INVENTORY_ID
-- ----------------------------
DROP SEQUENCE "ZOTION"."SEQ_INVENTORY_ID";
CREATE SEQUENCE "ZOTION"."SEQ_INVENTORY_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_MATERIAL_ID
-- ----------------------------
DROP SEQUENCE "ZOTION"."SEQ_MATERIAL_ID";
CREATE SEQUENCE "ZOTION"."SEQ_MATERIAL_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_OUTBOUND_DETAIL_ID
-- ----------------------------
DROP SEQUENCE "ZOTION"."SEQ_OUTBOUND_DETAIL_ID";
CREATE SEQUENCE "ZOTION"."SEQ_OUTBOUND_DETAIL_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_OUTBOUND_ORDER_ID
-- ----------------------------
DROP SEQUENCE "ZOTION"."SEQ_OUTBOUND_ORDER_ID";
CREATE SEQUENCE "ZOTION"."SEQ_OUTBOUND_ORDER_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for SEQ_WAREHOUSE_ID
-- ----------------------------
DROP SEQUENCE "ZOTION"."SEQ_WAREHOUSE_ID";
CREATE SEQUENCE "ZOTION"."SEQ_WAREHOUSE_ID" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Primary Key structure for table INBOUND_DETAIL
-- ----------------------------
ALTER TABLE "ZOTION"."INBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011589" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table INBOUND_DETAIL
-- ----------------------------
ALTER TABLE "ZOTION"."INBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011595" UNIQUE ("INBOUND_ORDER_CODE") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table INBOUND_DETAIL
-- ----------------------------
ALTER TABLE "ZOTION"."INBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011585" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011586" CHECK ("INBOUND_ORDER_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011587" CHECK ("MATERIAL_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011588" CHECK ("QUANTITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table INBOUND_DETAIL
-- ----------------------------
CREATE TRIGGER "ZOTION"."TRI_INBOUND_DETAIL_ID_AUTO" BEFORE INSERT ON "ZOTION"."INBOUND_DETAIL" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
declare
begin
	select seq_inbound_detail_id.nextval into :new.id from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table INBOUND_ORDER
-- ----------------------------
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011566" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table INBOUND_ORDER
-- ----------------------------
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011596" UNIQUE ("INBOUND_ORDER_CODE") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY DISABLE NOVALIDATE;

-- ----------------------------
-- Checks structure for table INBOUND_ORDER
-- ----------------------------
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011560" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011561" CHECK ("INBOUND_ORDER_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011562" CHECK ("WAREHOUSE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011563" CHECK ("INBOUND_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011564" CHECK ("OPERATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INBOUND_ORDER" ADD CONSTRAINT "SYS_C0011565" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table INBOUND_ORDER
-- ----------------------------
CREATE TRIGGER "ZOTION"."TRI_INBOUND_ORDER_ID_AUTO" BEFORE INSERT ON "ZOTION"."INBOUND_ORDER" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
declare
begin
	select seq_inbound_order_id.nextval into :new.id from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table INVENTORY
-- ----------------------------
ALTER TABLE "ZOTION"."INVENTORY" ADD CONSTRAINT "SYS_C0011584" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table INVENTORY
-- ----------------------------
ALTER TABLE "ZOTION"."INVENTORY" ADD CONSTRAINT "SYS_C0011580" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INVENTORY" ADD CONSTRAINT "SYS_C0011581" CHECK ("WAREHOUSE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INVENTORY" ADD CONSTRAINT "SYS_C0011582" CHECK ("MATERIAL_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."INVENTORY" ADD CONSTRAINT "SYS_C0011583" CHECK ("QUANTITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table INVENTORY
-- ----------------------------
CREATE TRIGGER "ZOTION"."TRI_INVENTORY_ID_AUTO" BEFORE INSERT ON "ZOTION"."INVENTORY" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
declare
begin
	select seq_inventory_id.nextval into :new.id from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table MATERIAL
-- ----------------------------
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011553" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table MATERIAL
-- ----------------------------
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011597" UNIQUE ("MATERIAL_CODE") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table MATERIAL
-- ----------------------------
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011545" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011546" CHECK ("MATERIAL_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011547" CHECK ("MATERIAL_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011548" CHECK ("UNIT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011549" CHECK ("MODEL" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011550" CHECK ("SPECIFICATION" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011551" CHECK ("MAINTAINER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."MATERIAL" ADD CONSTRAINT "SYS_C0011552" CHECK ("MODIFY_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table MATERIAL
-- ----------------------------
CREATE TRIGGER "ZOTION"."TRI_MATERIAL_ID_AUTO" BEFORE INSERT ON "ZOTION"."MATERIAL" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
declare
begin
	select seq_material_id.nextval into :new.id from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table OUTBOUND_DETAIL
-- ----------------------------
ALTER TABLE "ZOTION"."OUTBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011594" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table OUTBOUND_DETAIL
-- ----------------------------
ALTER TABLE "ZOTION"."OUTBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011598" UNIQUE ("OUTBOUND_ORDER_CODE") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table OUTBOUND_DETAIL
-- ----------------------------
ALTER TABLE "ZOTION"."OUTBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011590" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011591" CHECK ("OUTBOUND_ORDER_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011592" CHECK ("MATERIAL_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_DETAIL" ADD CONSTRAINT "SYS_C0011593" CHECK ("QUANTITY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table OUTBOUND_DETAIL
-- ----------------------------
CREATE TRIGGER "ZOTION"."TRI_OUTBOUND_DETAIL_ID_AUTO" BEFORE INSERT ON "ZOTION"."OUTBOUND_DETAIL" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
declare
begin
	select seq_outbound_detail_id.nextval into :new.id from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table OUTBOUND_ORDER
-- ----------------------------
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011573" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table OUTBOUND_ORDER
-- ----------------------------
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011599" UNIQUE ("OUTBOUND_ORDER_CODE") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table OUTBOUND_ORDER
-- ----------------------------
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011567" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011568" CHECK ("OUTBOUND_ORDER_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011569" CHECK ("WAREHOUSE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011570" CHECK ("OUTBOUND_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011571" CHECK ("OPERATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."OUTBOUND_ORDER" ADD CONSTRAINT "SYS_C0011572" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table OUTBOUND_ORDER
-- ----------------------------
CREATE TRIGGER "ZOTION"."TRI_OUTBOUND_ORDER_ID_AUTO" BEFORE INSERT ON "ZOTION"."OUTBOUND_ORDER" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
declare
begin
	select seq_outbound_order_id.nextval into :new.id from dual;
end;
/

-- ----------------------------
-- Primary Key structure for table WAREHOUSE
-- ----------------------------
ALTER TABLE "ZOTION"."WAREHOUSE" ADD CONSTRAINT "SYS_C0011559" PRIMARY KEY ("ID");

-- ----------------------------
-- Uniques structure for table WAREHOUSE
-- ----------------------------
ALTER TABLE "ZOTION"."WAREHOUSE" ADD CONSTRAINT "SYS_C0011600" UNIQUE ("WAREHOUSE_CODE") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table WAREHOUSE
-- ----------------------------
ALTER TABLE "ZOTION"."WAREHOUSE" ADD CONSTRAINT "SYS_C0011554" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."WAREHOUSE" ADD CONSTRAINT "SYS_C0011555" CHECK ("WAREHOUSE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."WAREHOUSE" ADD CONSTRAINT "SYS_C0011556" CHECK ("WAREHOUSE_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."WAREHOUSE" ADD CONSTRAINT "SYS_C0011557" CHECK ("MAINTAINER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "ZOTION"."WAREHOUSE" ADD CONSTRAINT "SYS_C0011558" CHECK ("MODIFY_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Triggers structure for table WAREHOUSE
-- ----------------------------
CREATE TRIGGER "ZOTION"."TRI_WAREHOUSE_ID_AUTO" BEFORE INSERT ON "ZOTION"."WAREHOUSE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
declare
begin
	select seq_warehouse_id.nextval into :new.id from dual;
end;
/
